version: "3.9"

services:
  bsc-geth:
    build: 
      context: .
      dockerfile: Dockerfile.bsc
      args:
        GIT_SOURCE: https://github.com/web3labs/bsc
        GIT_CHECKOUT_REF: master
    image: bsc-geth:docker-local